language: php
php:
- 5.5
- 5.6
- 7.0
install:
- COMPOSER_ROOT_VERSION=dev-master composer install
before_script:
- mkdir -p build/logs
script:
- vendor/bin/phpunit --coverage-clover build/logs/clover.xml
after_success:
- php vendor/bin/coveralls -v
