language: php
php:
- 5.5
- 5.6
- 7.0
install:
- COMPOSER_ROOT_VERSION=dev-master composer install
- wget https://github.com/satooshi/php-coveralls/releases/download/v1.0.1/coveralls.phar
- chmod +x coveralls.phar
before_script:
- mkdir -p build/logs
script:
- vendor/bin/phpunit --coverage-clover build/logs/clover.xml
after_success:
- php coveralls.phar --coverage_clover=build/logs/clover.xml -v
